import BeforeAuth from './pages/auth/BeforeAuth/BeforeAuth';
import ChooseInterest from './pages/auth/Account setup/ChooseInterest';
import Login from './pages/auth/Login/Login';
import OptionAuth from './pages/auth/OptionAuth/OptionAuth';
import SignUp from './pages/auth/SignUp/SignUp';
import ForgerPassword from './pages/auth/ForgetPassword/ForgetPassword';
import GetCode from './pages/auth/ForgetPassword/GetCode';
import ResetPassword from './pages/auth/ForgetPassword/ResetPassword';
import EditProfile from './pages/auth/Account setup/EditProfile';
export { ChooseInterest, OptionAuth, Login, BeforeAuth, SignUp, ForgerPassword, GetCode, ResetPassword, EditProfile };
